### ISSUE TITLE
WIEGO Presence - only 55 countries are colored but there are 62 WIEGO Presence countries

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#12]
The content type listing for wiego presence shows that we have created content for 62 countries
Only 55 countries are colored.

Two countries that should be colored and are not are Canada and United Kingdom.

neither of those countries contain membership info or board info but they do contain data for WIEGO team and also for Programme Partners and Activities

**Comment by wiegoglobal** [comment]
Canada and United Kingdom are still not colored and we have populated them with data.
Please advise on the status of this issue

**Comment by garygoldman** [comment]
We have reviewed the functionality and it’s working fine. We are getting all the 62 WIEGO Presence countries on the front. But yes, these countries are not appearing on the map because the name of the countries are not matching with the name that we have in the map shapefile.  
 
e.g. in case of UK, in our shapefile we have “United Kingdom” but from the backend we are getting “United Kingdom of Great Britain & Northern Ireland”.
 
We can update the name of the countries in our shapefile. Can you please provide the name of countries those are not appearing in map? Are you following http://unstats.un.org/unsd/methods/m49/m49alpha.htm? If yes, then we can update the countries name in shapefile with this format.
 
In case of Canada , there is an extra space in the regions taxonomy. Once you will correct this in backend, it will automatically reflect on the map.

**Comment by wiegoglobal** [comment]
Gary, please clarify what you mean by, "In case of Canada , there is an extra space in the regions taxonomy." I have gone into the taxonomy on the production site and checked both the region name "Other Developed Countries" and also "Canada." I do not see an "extra space" at least in the title of the term. I do not know where else to look.

With regard to the taxonomy, we very carefully constructed the list of country names as we wanted them to be written and also under respective regions. I will look for the previous communication on this.

Where is the "map shape file" and how can we access this in the future to update/make corrections?"

**Comment by garygoldman** [comment]
Patricia, we will check for Canada and Other Developed Countries. If you could provide us with the list of 7 countries that are not highlighted in WIEGO presence (you mentioned 55 out of 62 worked), it will make addressing the issue much easier.

**Comment by wiegoglobal** [comment]
Hi Gary,

Here are the two emails that refer to the country names and listings.
Please refer to that list in the taxonomy and use what we have in the taxonomy for the "UK." All of the countries and regions were finalized Aug. 10. and we expected CSF to use that list for the map.


Sent by me (Patricia Carney)
Aug 10 1:39 pm
The taxonomy on the production site has been updated and reflects the names of the new regions and countries are associated with their respective parent groupings.

Sent by me in response to a previous email from Gary
Aug 11 11:36 a.m.
I responded to an email you had sent previously, please see your comment in the message:
_As long as the regions match and the list of countries is finalized on the production server, we're all good._

**Comment by garygoldman** [comment]
Hi Patricia,

Thank you for sending the trail of emails. Will you be able to send the list of 7 countries that are missing (if you have them), or would you like me to cross-reference?

**Comment by wiegoglobal** [comment]
Missing countries on map:
Canada
China, Hong Kong, Special Administrative Region
Philippines
Republic of Korea
Republic of Moldova
United Kingdom of Great Britain & Northern Ireland
Venezuela, Bolivarian Republic of
