### ISSUE TITLE
Duplicate programme names in WIEGO presence sidebar under programme activities & partners

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#17]
We should only see once instance of any name. For example:
For the region south asia, in WIEGO Presence, under Programme Partners & Activities, "Organization & Representation" is listed at least seven times. 
![presence-dup-prgram-names](https://cloud.githubusercontent.com/assets/22031182/18567585/38022ba4-7b6f-11e6-83c2-9d2096f2e37e.jpg)

**Comment by garygoldman** [comment]
Hi Patricia,

WIEGO Presence for South Asia aggregates the information that was added in all of its countries (e.g. Pakistan, India, Nepal). Below are three screenshots for these three countries, which each have Organization & Representation. Is this not what the feature should do? 

![screen shot 2016-09-16 at 12 20 27 pm](https://cloud.githubusercontent.com/assets/6609331/18593150/1a2bbb2e-7c08-11e6-98f8-b3fb14a36724.png)

![screen shot 2016-09-16 at 12 20 05 pm](https://cloud.githubusercontent.com/assets/6609331/18593154/1d897a86-7c08-11e6-989b-eb7f2648f417.png)

![screen shot 2016-09-16 at 12 19 45 pm](https://cloud.githubusercontent.com/assets/6609331/18593157/20633382-7c08-11e6-9ae8-c8d02740863a.png)

**Comment by garygoldman** [comment]
Dear Patricia,

As you know, the regional information is coming from different countries. In the case of South Asia,  you have “Organization & Representation” for Sri Lanka, Nepal, India, Pakistan etc. 

Please suggest the condition on which basis we can hide this, because we have URL field too for each Programme Name, and it can be different for each country. How do you suggest we select one? 
 
Have a look on below admin URLs, this may make things clearer when I say "a URL field for each Programme Name":
 
http://wiego.org/node/53146/edit?destination=admin%2Fcontent%2Fnode%2Foverview
http://wiego.org/node/53266/edit?destination=admin%2Fcontent%2Fnode%2Foverview
http://wiego.org/node/53281/edit?destination=admin%2Fcontent%2Fnode%2Foverview%3Fpage%3D1
http://wiego.org/node/53261/edit?destination=admin%2Fcontent%2Fnode%2Foverview
