### ISSUE TITLE
City data error

### ISSUE THREAD

**Issue by jaharvey711** [WIEGO-Global/wiegodashboard#2]
The top city data graph, “employment inside and outside the informal sector…” is missing data under the “total” indicator. The graph only shows total outside the informal sector, when it should show inside and outside. I checked the spreadsheet on sheetnode and the data is there, it just isn’t appearing in the graph. 
![2016-09-07 10_23_08-statistics _ wiego](https://cloud.githubusercontent.com/assets/22055030/18315498/3d67d944-74e5-11e6-8ed9-c2030aa5bca2.png)

**Comment by wiegoglobal** [comment]
CSF is looking into it.

**Comment by garygoldman** [comment]
We have fixed the issue. http://wiego.org/dashboard/statistics/east-asia-southeast-asia/china/china---6-cities. For context, this issue was from the way the data had been entered in the spreadsheet, as there were minor spelling differences between the indicator. See below!

![unnamed-2](https://cloud.githubusercontent.com/assets/6609331/18552277/b92565de-7b29-11e6-9056-7dd6096d3937.png)
