### ISSUE TITLE
Maps and charts saving and sharing functionality

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#21]
Maps and charts have “save as” functionality. The maps really shouldn’t because they are not conveying any data that would be useful to anyone and they do not contain titles. Charts are also downloadable and have labels and titles but no source information. They should contain source information as WIEGO.

There is an issue in the chart label functionality. If I click on the colour labels, that item disappears from the chart.

I was looking forward to tweeting and sharing tables and properly documented charts directly from the tool. This was discussed in one of the meetings. So far, that doesn’t work. If I share the statistical report, it just sends me a link to the page, the charts don't show up in Twitter or Facebook.

**Comment by garygoldman** [comment]
**Map**
Understood. We will look into whether we can suppress the download icon for the map. 

**Chart Labels**
Your comment on chart label is not a bug/issue, but a feature of the visualization. This allows the user to focus on one specific subgroup of the chart (e.g. if you'd only like to display data for Women). We will look at the possibility of fixing the axis to 100% in order to accurately display the selected data. 

**Sharing**
As for the sharing of specific graphs, you presently have two options: (1) share the entire page and (2) download specific graphs and share them manually. For (1), what would you like to appear when the entire page is shared? Do you want an image of the entire page? We'll also look into the possibility of sharing individual charts directly through FB/Twitter. This may not be available through the open-source library, but we'll have an answer to this one by early next week.

**Comment by wiegoglobal** [comment]
Hi Gary,

This was an issue presented by another team member. I'll ask her to respond directly in this space.

 Pat

**Comment by garygoldman** [comment]
Both issues have been addressed. 
               
http://wiego.org/dashboard/statistics (you cannot download the map anymore)
http://wiego.org/dashboard/statistics/south-asia/india (you now cannot click on the label at the bottom, which makes it less confusing)
