### ISSUE TITLE
Annex A: access to Git

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#4]
From Annex A:
Please provide the following:
"The Control Version System (CVS) that will be used is Git, and CSF will provide access to it to the WIEGO focal points"
- Do we need to have CSF's login credentials for their Git account on our server, or will we have the same access to the information using our own wiego login credentials for Git?

[Annex A-CSF- WIEGO comments - CSF Comments_GG_r2-2 plus PB.docx](https://github.com/WIEGO-Global/wiegodashboard/files/459480/Annex.A-CSF-.WIEGO.comments.-.CSF.Comments_GG_r2-2.plus.PB.docx)

**Comment by wiegoglobal** [comment]
Please advise.

**Comment by garygoldman** [comment]
Patricia - let me get back to you on this one by tomorrow morning.

--
Gary Goldman
Senior Programme Advisor



205 East 42nd Street, Suite 15050
New York, NY 10017 USA

+1.212.500.1335
www.communitysystemsfoundation.org

**Comment by garygoldman** [comment]
Hi Pablo, 

We are not using Git for this project but Acquia https://www.acquia.com. For window authentication please use wiego username and wiego for password. To download the latest file and database, please get logged-in into Acquia. You will get the options for backup to download the same.

Let me know if you have any questions.

**Comment by numeroteca** [comment]
I am a bit confused. So I need to log in in Acquia (therefore create one user) and then inside it is the version control system where I can track changes to the code?
In the Annex A it was said that you would be using git.

**Comment by garygoldman** [comment]
Hi Pablo,

The original document did indeed state we would be sign Github. We're happy to upload all the documents to Github if you prefer this. 

The host provider for WIEGO is a platform called Aquia, which you likely have user information for. Because of this, CSF has been using the “Acquia Dev Desktop” tool. This allows us to install and configure any Acquia-based website locally.  We can make a clone of any available development environment using this tool. For our development work, we therefore created clone from dev.wiego.org. 

Let me know how you'd like to proceed.

**Comment by numeroteca** [comment]
I'll ask for an access to Acquia. I don't have access yet.

However I am looking for the control version system of the developed code, to be ale to track the changes that you implement. It was supposed to be git (github is just a web-based Git repository hosting service). Is there a control version system installed in Acquia? Which control version system are you using?

Thanks.

**Comment by garygoldman** [comment]
Why we are using Acquia Dev Desktop
 
1)      Acquia Dev Desktop provide built-in Acquia Cloud integration. WIEGO is hosted on Acquia Cloud.

2)      We can clone any of your Acquia Cloud sites, including any Acquia Cloud environment to work on them offline in Dev Desktop. Clone from any of Acquia Cloud environments (dev, stage, prod, or custom environments).

3)      Using this we can easily make any code, database, or file changes on Acquia Cloud or on your local machine and synchronize them.

4)      WIEGO have the concept of multisite. By using Acquia Dev Desktop, we can take advantage of Drupal multisite to maintain one code base that runs multiple sites using different databases and files.

5)      We can add modules to our local file system and push code to add those modules to our Acquia Cloud site without ever learning Git.

6)      On each commit, Acquia create a checkout point by date (by default). We can always roll back our changes on previous checkout point easily.

7)      We can also use Git in parallel but we didn’t do that because Acquia Dev Desktop already providing strong and easy to handle UI. We can achieve all our development requirement using this.

 
 
Also, in Acquia we can track all our activities of any date from https://insight.acquia.com/activity/all?s=468451
 
Please find below URLs in support of above mentioned points
 
https://www.acquia.com/products-services/dev-desktop
https://dev.acquia.com/blog/streamline-your-local-drupal-workflow-acquia-dev-desktop-2
https://docs.acquia.com/dev-desktop
https://www.drupaleasy.com/blogs/ultimike/2014/09/drupal-career-online-pros-cons-acquia-dev-desktop-version-2
 
Let me know if this works!

**Comment by numeroteca** [comment]
Thanks for the detailed answer. 
So I need access to the acquia account! 
If I create an user could you provide access?

**Comment by garygoldman** [comment]
That is correct. Patricia had provided our developer Rudolph with access to the Acquia account with the username webmaster98. I have asked him to provide the password and will revert shortly.

**Comment by numeroteca** [comment]
In case you have a password to send, please send it directly to my email. Thanks!

**Comment by numeroteca** [comment]
I've managed to see all the commits in the git installed in acquia (webmaster98@svn-634.devcloud.hosting.acquia.com:webmaster98.git) but I don't see changes related to the dashboard development. I see test commits by abhishek in December 2015, all the others are by isovera people and not related.

Could you guide me to find where are the commits related to the dashboard development?

**Comment by numeroteca** [comment]
I just received from Gary an email indicating that changes to the dashboard can be seen at "develop" branch. So the git url from the previous comment was correct!
